### ISSUE TITLE
'data.csv' referenced after question 47 but no reference to what this table is

### ISSUE THREAD

**Issue by adraper2** [kwaldenphd/tabular-data-python#2]
Should students make a data.csv matching the table above before running the code below. I have added a note above the code to do so for the time being but I am unsure if that's correct.

**Comment by kwaldenphd** [comment]
Good catch--the data.csv file referenced in 47 is more of a hypothetical example in which they had a file with data resembling the structure/format outlined in that section of the lab. Won't actually run that code in lecture--will talk them through the syntax. Code is more of a reference for them to go back to if needed when working with their own datasets. Does that make sense?

**Comment by adraper2** [comment]
Yes, makes sense! I will close this issue then.
